CREATE TABLE questions (
  id bigint generated by default as identity primary key,
  question text not null,
  options text[] not null,
  answer text not null
);

INSERT INTO questions (question, options, answer) VALUES
('What is the capital of France?', '{"London", "Paris", "Berlin", "Madrid"}', 'Paris'),
('Which planet is known as the Red Planet?', '{"Venus", "Mars", "Jupiter", "Saturn"}', 'Mars'),
('What is the largest mammal?', '{"Elephant", "Blue Whale", "Giraffe", "Great White Shark"}', 'Blue Whale');