-- schema.sql

-- Users table
create table users (
  id bigint generated by default as identity primary key,
  auth_uid uuid null,
  name text null,
  email text null,
  guest boolean default false not null,
  created_at timestamp with time zone default now() null
);

-- Conversations table
create table conversations (
  id bigint generated by default as identity primary key,
  user_id bigint references users not null,
  title text null,
  mode text default 'chat' null,
  created_at timestamp with time zone default now() null
);

-- Messages table
create table messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations not null,
  user_id bigint references users not null,
  role text not null,
  content text not null,
  created_at timestamp with time zone default now() null
);

-- Developer progress logs
create table developer_progress_logs (
    id bigint generated by default as identity primary key,
    user_id text null,
    conversation_id text null,
    prompt text null,
    assistant text null,
    meta jsonb null,
    created_at timestamp with time zone default now() not null
);
