
CREATE TABLE summaries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE quizzes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  questions jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE recents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  tool text not null,
  tool_id bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
